# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Packnplay < Formula
  desc "Development container tool with seamless AI coding agent support"
  homepage "https://github.com/obra/packnplay"
  version "1.2.1-test"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/obra/packnplay/releases/download/v1.2.1-test/packnplay_1.2.1-test_Darwin_x86_64.tar.gz"
      sha256 "f44e1fffb8431341fc0c3414f2479c8788b31d7a1ce0691c4f0b5109f1ef0151"

      def install
        bin.install "packnplay"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/obra/packnplay/releases/download/v1.2.1-test/packnplay_1.2.1-test_Darwin_arm64.tar.gz"
      sha256 "414a4b260b7918eb23ceb303a7c66ac58f7adffdb28b5eef577227275b1b8100"

      def install
        bin.install "packnplay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/obra/packnplay/releases/download/v1.2.1-test/packnplay_1.2.1-test_Linux_x86_64.tar.gz"
      sha256 "edaf924341c6fbb80724608c57848e50aee7c01643de339e7caf113b31cd966b"
      def install
        bin.install "packnplay"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/obra/packnplay/releases/download/v1.2.1-test/packnplay_1.2.1-test_Linux_arm64.tar.gz"
      sha256 "32bfd864961cd952661ee0a0fedbe92abb90d584dd1d25e90490ebd5173678a5"
      def install
        bin.install "packnplay"
      end
    end
  end

  test do
    system "#{bin}/packnplay", "version"
  end
end
