# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Packnplay < Formula
  desc "Development container tool with seamless AI coding agent support"
  homepage "https://github.com/obra/packnplay"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/obra/packnplay/releases/download/v1.1.0/packnplay_1.1.0_Darwin_x86_64.tar.gz"
      sha256 "a62de8a173e3ce63aeafa29d60253839fc63b4ab322dfb464b7c97f3267f4c74"

      def install
        bin.install "packnplay"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/obra/packnplay/releases/download/v1.1.0/packnplay_1.1.0_Darwin_arm64.tar.gz"
      sha256 "51e23a976c215376bf4e0e9441e470423ba31853f532b21932e241709423e679"

      def install
        bin.install "packnplay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/obra/packnplay/releases/download/v1.1.0/packnplay_1.1.0_Linux_x86_64.tar.gz"
      sha256 "57556a21096dcb8154c4304075652c7abe1b15b6945bea5a8ab5f2455e7d47e7"
      def install
        bin.install "packnplay"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/obra/packnplay/releases/download/v1.1.0/packnplay_1.1.0_Linux_arm64.tar.gz"
      sha256 "2a2e9820856deb4cfd5f0929d15748015d89421fba31313b092ab7ce26189bdb"
      def install
        bin.install "packnplay"
      end
    end
  end

  test do
    system "#{bin}/packnplay", "--version"
  end
end
